export const UPLOAD_FIXED_IMAGE_REQUEST = "UPLOAD_FIXED_IMAGE_REQUEST";
export const UPLOAD_FIXED_IMAGE_SUCCESS = "UPLOAD_FIXED_IMAGE_SUCCESS";
export const UPLOAD_FIXED_IMAGE_FAILURE = "UPLOAD_FIXED_IMAGE_FAILURE";

export const CLEAN_FIXED_IMAGES = "CLEAN_FIXED_IMAGES";
export const DELETED_FIXED_IMAGES = "DELETED_FIXED_IMAGES";

export const DELETE_FIXED_IMAGES_FROM_STORE = "DELETE_FIXED_IMAGES_FROM_STORE";

export const SET_UPLOADED_HEADERS = "SET_UPLOADED_HEADERS";

