export const FETCH_MEMBERS_BY_PAGE_REQUEST = "FETCH_MEMBERS_BY_PAGE_REQUEST";
export const FETCH_MEMBERS_BY_PAGE_SUCCESS = "FETCH_MEMBERS_BY_PAGE_SUCCESS";
export const FETCH_MEMBERS_BY_PAGE_FAILURE = "FETCH_MEMBERS_BY_PAGE_FAILURE";
