export const FETCH_MEMBERS_BY_PAGE_REQUEST = "FETCH_MEMBERS_BY_PAGE_REQUEST";
export const FETCH_MEMBERS_BY_PAGE_SUCCESS = "FETCH_MEMBERS_BY_PAGE_SUCCESS";
export const FETCH_MEMBERS_BY_PAGE_FAILURE = "FETCH_MEMBERS_BY_PAGE_FAILURE";

export const ADD_MEMBER_REQUEST = "ADD_MEMBER_REQUEST";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAILURE = "ADD_MEMBER_FAILURE";

export const FETCH_EDUCATIONS_REQUEST = "FETCH_EDUCATIONS_REQUEST";
export const FETCH_EDUCATIONS_SUCCESS = "FETCH_EDUCATIONS_SUCCESS";
export const FETCH_EDUCATIONS_FAILURE = "FETCH_EDUCATIONS_FAILURE";

export const FETCH_MEMBERS_FORM_REQUEST = "FETCH_MEMBERS_FORM_REQUEST";
export const FETCH_MEMBERS_FORM_SUCCESS = "FETCH_MEMBERS_FORM_SUCCESS";
export const FETCH_MEMBERS_FORM_FAILURE = "FETCH_MEMBERS_FORM_FAILURE";

export const FETCH_CONTACT_TYPES_REQUEST = "FETCH_CONTACT_TYPES_REQUEST";
export const FETCH_CONTACT_TYPES_SUCCESS = "FETCH_CONTACT_TYPES_SUCCESS";
export const FETCH_CONTACT_TYPES_FAILURE = "FETCH_CONTACT_TYPES_FAILURE";

export const DELETE_MEMBER_REQUEST = "DELETE_MEMBER_REQUEST";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const DELETE_MEMBER_FAILURE = "DELETE_MEMBER_FAILURE";

export const FETCH_MEMBER_DETAILS_REQUEST = "FETCH_MEMBER_DETAILS_REQUEST";
export const FETCH_MEMBER_DETAILS_SUCCESS = "FETCH_MEMBER_DETAILS_SUCCESS";
export const FETCH_MEMBER_DETAILS_FAILURE = "FETCH_MEMBER_DETAILS_FAILURE";

export const FETCH_MEMBER_FOR_EDIT_REQUEST = "FETCH_MEMBER_FOR_EDIT_REQUEST";
export const FETCH_MEMBER_FOR_EDIT_SUCCESS = "FETCH_MEMBER_FOR_EDIT_SUCCESS";
export const FETCH_MEMBER_FOR_EDIT_FAILURE = "FETCH_MEMBER_FOR_EDIT_FAILURE";

export const MEMBER_EDIT_REQUEST = "MEMBER_EDIT_REQUEST";
export const MEMBER_EDIT_SUCCESS_FAILURE = "MEMBER_EDIT_SUCCESS_FAILURE";

export const TRANSFER_MEMBER_DELETE = "TRANSFER_MEMBER_DELETE";
export const CLEAN_MEMBER = "CLEAN_MEMBER";
