export const UPLOAD_VIDEO_REQUEST = "UPLOAD_VIDEO_REQUEST";
export const UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS";
export const UPLOAD_VIDEO_FAILURE = "UPLOAD_VIDEO_FAILURE";

export const CLEAN_VIDEOS = "CLEAN_VIDEOS";
export const DELETED_VIDEOS = "DELETED_VIDEOS";

export const DELETE_VIDEO_FROM_STORE = "DELETE_VIDEO_FROM_STORE";
