export const FETCH_APPLICANTS_REQUEST = "FETCH_APPLICANTS_REQUEST";
export const FETCH_APPLICANTS_SUCCESS = "FETCH_APPLICANTS_SUCCESS";
export const FETCH_APPLICANTS_FAILURE = "FETCH_APPLICANTS_FAILURE";

export const APPLICANT_EDIT_REQUEST = "APPLICANT_EDIT_REQUEST";
export const APPLICANT_EDIT_SUCCESS = "APPLICANT_EDIT_SUCCESS";
export const APPLICANT_EDIT_FAILURE = "APPLICANT_EDIT_FAILURE";
