export const FETCH_PAST_EVENTS_REQUEST = "FETCH_PAST_EVENTS_REQUEST";
export const FETCH_PAST_EVENTS_SUCCESS = "FETCH_PAST_EVENTS_SUCCESS";
export const FETCH_PAST_EVENTS_FAILURE = "FETCH_PAST_EVENTS_FAILURE";

export const FETCH_UPCOMING_EVENTS_REQUEST = "FETCH_UPCOMING_EVENTS_REQUEST";
export const FETCH_UPCOMING_EVENTS_SUCCESS = "FETCH_UPCOMING_EVENTS_SUCCESS";
export const FETCH_UPCOMING_EVENTS_FAILURE = "FETCH_UPCOMING_EVENTS_FAILURE";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";

export const TRANSFER_EVENT_DELETE = "TRANSFER_EVENT_DELETE";

export const FETCH_EVENT_FOR_EDIT_REQUEST = "FETCH_EVENT_FOR_EDIT_REQUEST";
export const FETCH_EVENT_FOR_EDIT_SUCCESS = "FETCH_EVENT_FOR_EDIT_SUCCESS";
export const FETCH_EVENT_FOR_EDIT_FAILURE = "FETCH_EVENT_FOR_EDIT_FAILURE";

export const ADD_EVENT_REQUEST = "ADD_EVENT_REQUEST";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAILURE = "ADD_EVENT_FAILURE";

export const FETCH_EVENT_DETAILS_REQUEST = "FETCH_EVENT_DETAILS_REQUEST";
export const FETCH_EVENT_DETAILS_SUCCESS = "FETCH_EVENT_DETAILS_SUCCESS";
export const FETCH_EVENT_DETAILS_FAILURE = "FETCH_EVENT_DETAILS_FAILURE";

export const FETCH_EVENTS_BY_PAGE_REQUEST = "FETCH_EVENTS_BY_PAGE_REQUEST";
export const FETCH_EVENTS_BY_PAGE_SUCCESS = "FETCH_EVENTS_BY_PAGE_SUCCESS";
export const FETCH_EVENTS_BY_PAGE_FAILURE = "FETCH_EVENTS_BY_PAGE_FAILURE";

export const EVENT_EDIT_REQUEST = "EVENT_EDIT_REQUEST";
export const EVENT_EDIT_SUCCESS = "EVENT_EDIT_SUCCESS";
export const EVENT_EDIT_FAILURE = "EVENT_EDIT_FAILURE";

export const CLEAN_EVENT = "CLEAN_EVENT";

export const EDIT_AGENDAS = "EDIT_AGENDAS";

export const EDIT_IMAGES = "EDIT_IMAGES";
export const DELETE_EVENT_IMAGE_FROM_STORE = "DELETE_EVENT_IMAGE_FROM_STORE";

export const FETCH_ALL_SPEAKERS_REQUEST = "FETCH_ALL_SPEAKERS_REQUEST";
export const FETCH_ALL_SPEAKERS_SUCCESS = "FETCH_ALL_SPEAKERS_SUCCESS";
export const FETCH_ALL_SPEAKERS_FAILURE = "FETCH_ALL_SPEAKERS_FAILURE";

export const ADD_EVENT_DETAILS = "ADD_EVENT_DETAILS";

export const SET_UPLOADED_PHOTOS = "SET_UPLOADED_PHOTOS";

export const ADD_EVENT_BLOCK_REQUEST = "ADD_EVENT_BLOCK_REQUEST";
export const ADD_EVENT_BLOCK_SUCCESS = "ADD_EVENT_BLOCK_SUCCESS";
export const ADD_EVENT_BLOCK_FAILURE = "ADD_EVENT_BLOCK_FAILURE";

export const EVENT_EDIT_BLOCK_REQUEST = "EVENT_EDIT_BLOCK_REQUEST";
export const EVENT_EDIT_BLOCK_SUCCESS = "EVENT_EDIT_BLOCK_SUCCESS";
export const EVENT_EDIT_BLOCK_FAILURE = "EVENT_EDIT_BLOCK_FAILURE";

export const DELETE_BLOCK_REQUEST = "DELETE_BLOCK_REQUEST";
export const DELETE_BLOCK_SUCCESS = "DELETE_BLOCK_SUCCESS";
export const DELETE_BLOCK_FAILURE = "DELETE_BLOCK_FAILURE";
