export const FETCH_PAST_EVENTS_REQUEST = "FETCH_PAST_EVENTS_REQUEST";
export const FETCH_PAST_EVENTS_SUCCESS = "FETCH_PAST_EVENTS_SUCCESS";
export const FETCH_PAST_EVENTS_FAILURE = "FETCH_PAST_EVENTS_FAILURE";

export const FETCH_UPCOMING_EVENTS_REQUEST = "FETCH_UPCOMING_EVENTS_REQUEST";
export const FETCH_UPCOMING_EVENTS_SUCCESS = "FETCH_UPCOMING_EVENTS_SUCCESS";
export const FETCH_UPCOMING_EVENTS_FAILURE = "FETCH_UPCOMING_EVENTS_FAILURE";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";

export const TRANSFER_EVENT_DELETE = "TRANSFER_EVENT_DELETE";

export const FETCH_EVENT_FOR_EDIT_REQUEST = "FETCH_EVENT_FOR_EDIT_REQUEST";
export const FETCH_EVENT_FOR_EDIT_SUCCESS = "FETCH_EVENT_FOR_EDIT_SUCCESS";
export const FETCH_EVENT_FOR_EDIT_FAILURE = "FETCH_EVENT_FOR_EDIT_FAILURE";
