export const ON_LOGIN_REQUEST = "ON_LOGIN_REQUEST";
export const ON_LOGIN_SUCCESS = "ON_LOGIN_SUCCESS";
export const ON_LOGIN_FAILURE = "ON_LOGIN_FAILURE";

export const AUTHORIZE_REQUEST = "AUTHORIZE_REQUEST";
export const AUTHORIZE_SUCCESS = "AUTHORIZE_SUCCESS";
export const AUTHORIZE_FAILURE = "AUTHORIZE_FAILURE";
