export const FETCH_ORGANIZATIONS_REQUEST = "FETCH_ORGANIZATIONS_REQUEST";
export const FETCH_ORGANIZATIONS_SUCCESS = "FETCH_ORGANIZATIONS_SUCCESS";
export const FETCH_ORGANIZATIONS_FAILURE = "FETCH_ORGANIZATIONS_FAILURE";

export const FETCH_ORGANIZATIONS_TABLE_REQUEST =
  "FETCH_ORGANIZATIONS_TABLE_REQUEST";
export const FETCH_ORGANIZATIONS_TABLE_SUCCESS =
  "FETCH_ORGANIZATIONS_TABLE_SUCCESS";
export const FETCH_ORGANIZATIONS_TABLE_FAILURE =
  "FETCH_ORGANIZATIONS_TABLE_FAILURE";

export const ADD_ORGANIZATION_REQUEST = "ADD_ORGANIZATION_REQUEST";
export const ADD_ORGANIZATION_SUCCESS = "ADD_ORGANIZATION_SUCCESS";
export const ADD_ORGANIZATION_FAILURE = "ADD_ORGANIZATION_FAILURE";

export const DELETE_ORGANIZATION_REQUEST = "DELETE_ORGANIZATION_REQUEST";
export const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS";
export const DELETE_ORGANIZATION_FAILURE = "DELETE_ORGANIZATION_FAILURE";

export const FETCH_ORGANIZATION_DETAILS_REQUEST =
  "FETCH_ORGANIZATION_DETAILS_REQUEST";
export const FETCH_ORGANIZATION_DETAILS_SUCCESS =
  "FETCH_ORGANIZATION_DETAILS_SUCCESS";
export const FETCH_ORGANIZATION_DETAILS_FAILURE =
  "FETCH_ORGANIZATION_DETAILS_FAILURE";

export const ORGANIZATION_EDIT_REQUEST = "ORGANIZATION_EDIT_REQUEST";
export const ORGANIZATION_EDIT_SUCCESS_FAILURE =
  "ORGANIZATION_EDIT_SUCCESS_FAILURE";

export const CLEAN_ORGANIZATION = "CLEAN_ORGANIZATION";

export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const FETCH_POSITIONS_REQUEST = "FETCH_POSITIONS_REQUEST";
export const FETCH_POSITIONS_SUCCESS = "FETCH_POSITIONS_SUCCESS";
export const FETCH_POSITIONS_FAILURE = "FETCH_POSITIONS_FAILURE";

export const FETCH_POSITIONS_ALL_REQUEST = "FETCH_POSITIONS_ALL_REQUEST";
export const FETCH_POSITIONS_ALL_SUCCESS = "FETCH_POSITIONS_ALL_SUCCESS";
export const FETCH_POSITIONS_ALL_FAILURE = "FETCH_POSITIONS_ALL_FAILURE";

export const ADD_POSITION_REQUEST = "ADD_POSITION_REQUEST";
export const ADD_POSITION_SUCCESS = "ADD_POSITION_SUCCESS";
export const ADD_POSITION_FAILURE = "ADD_POSITION_FAILURE";

export const FETCH_CATEGORIES_ALL_REQUEST = "FETCH_CATEGORIES_ALL_REQUEST";
export const FETCH_CATEGORIES_ALL_SUCCESS = "FETCH_CATEGORIES_ALL_SUCCESS";
export const FETCH_CATEGORIES_ALL_FAILURE = "FETCH_CATEGORIES_ALL_FAILURE";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

export const POSITION_EDIT_REQUEST = "POSITION_EDIT_REQUEST";
export const POSITION_EDIT_SUCCESS_FAILURE = "POSITION_EDIT_SUCCESS_FAILURE";

export const DELETE_POSITION_REQUEST = "DELETE_POSITION_REQUEST";
export const DELETE_POSITION_SUCCESS = "DELETE_POSITION_SUCCESS";
export const DELETE_POSITION_FAILURE = "DELETE_POSITION_FAILURE";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

export const CATEGORY_EDIT_REQUEST = "CATEGORY_EDIT_REQUEST";
export const CATEGORY_EDIT_SUCCESS_FAILURE = "CATEGORY_EDIT_SUCCESS_FAILURE";
