export const FETCH_NEWS_BY_PAGE_REQUEST = "FETCH_NEWS_BY_PAGE_REQUEST";
export const FETCH_NEWS_BY_PAGE_SUCCESS = "FETCH_NEWS_BY_PAGE_SUCCESS";
export const FETCH_NEWS_BY_PAGE_FAILURE = "FETCH_NEWS_BY_PAGE_FAILURE";

export const FETCH_NEWS_DETAILS_REQUEST = "FETCH_NEWS_DETAILS_REQUEST";
export const FETCH_NEWS_DETAILS_SUCCESS = "FETCH_NEWS_DETAILS_SUCCESS";
export const FETCH_NEWS_DETAILS_FAILURE = "FETCH_NEWS_DETAILS_FAILURE";

export const ADD_NEWS_REQUEST = "ADD_NEWS_REQUEST";
export const ADD_NEWS_SUCCESS = "ADD_NEWS_SUCCESS";
export const ADD_NEWS_FAILURE = "ADD_NEWS_FAILURE";

export const DELETE_NEWS_REQUEST = "DELETE_NEWS_REQUEST";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_FAILURE = "DELETE_NEWS_FAILURE";

export const TRANSFER_NEWS_DELETE = "TRANSFER_NEWS_DELETE";

export const NEWS_EDIT_REQUEST = "NEWS_EDIT_REQUEST";
export const NEWS_EDIT_SUCCESS_FAILURE = "NEWS_EDIT_SUCCESS_FAILURE";

export const DELETE_NEWS_IMAGE_FROM_STORE = "DELETE_NEWS_IMAGE_FROM_STORE";

export const ADD_NEWS_DETAILS = "ADD_NEWS_DETAILS";

export const ADD_NEWS_DETAILS_REQUEST = "ADD_NEWS_DETAILS_REQUEST";
export const ADD_NEWS_DETAILS_SUCCESS = "ADD_NEWS_DETAILS_SUCCESS";
export const ADD_NEWS_DETAILS_FAILURE = "ADD_NEWS_DETAILS_FAILURE";

export const FETCH_NEWS_BLOCK_DETAILS_REQUEST =
  "FETCH_NEWS_BLOCK_DETAILS_REQUEST";
export const FETCH_NEWS_BLOCK_DETAILS_SUCCESS =
  "FETCH_NEWS_BLOCK_DETAILS_SUCCESS";
export const FETCH_NEWS_BLOCK_DETAILS_FAILURE =
  "FETCH_NEWS_BLOCK_DETAILS_FAILURE";

export const DELETE_NEWS_BLOCK_REQUEST = "DELETE_NEWS_BLOCK_REQUEST";
export const DELETE_NEWS_BLOCK_SUCCESS = "DELETE_NEWS_BLOCK_SUCCESS";
export const DELETE_NEWS_BLOCK_FAILURE = "DELETE_NEWS_BLOCK_FAILURE";

export const NEWS_EDIT_BLOCK_REQUEST = "NEWS_EDIT_BLOCK_REQUEST";
export const NEWS_EDIT_BLOCK_SUCCESS = "NEWS_EDIT_BLOCK_SUCCESS";
export const NEWS_EDIT_BLOCK_FAILURE = "NEWS_EDIT_BLOCK_FAILURE";

