export const FETCH_NEWS_BY_PAGE_REQUEST = "FETCH_NEWS_BY_PAGE_REQUEST";
export const FETCH_NEWS_BY_PAGE_SUCCESS = "FETCH_NEWS_BY_PAGE_SUCCESS";
export const FETCH_NEWS_BY_PAGE_FAILURE = "FETCH_NEWS_BY_PAGE_FAILURE";

export const FETCH_NEWS_DETAILS_REQUEST = "FETCH_NEWS_DETAILS_REQUEST";
export const FETCH_NEWS_DETAILS_SUCCESS = "FETCH_NEWS_DETAILS_SUCCESS";
export const FETCH_NEWS_DETAILS_FAILURE = "FETCH_NEWS_DETAILS_FAILURE";

export const ADD_NEWS_REQUEST = "ADD_NEWS_REQUEST";
export const ADD_NEWS_SUCCESS = "ADD_NEWS_SUCCESS";
export const ADD_NEWS_FAILURE = "ADD_NEWS_FAILURE";
