export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";

export const CLEAN_IMAGES = "CLEAN_IMAGES";
export const DELETED_IMAGES = "DELETED_IMAGES";

export const UPLOAD_ONE_IMAGE_REQUEST = "UPLOAD_ONE_IMAGE_REQUEST";
export const UPLOAD_ONE_IMAGE_SUCCESS = "UPLOAD_ONE_IMAGE_SUCCESS";
export const UPLOAD_ONE_IMAGE_FAILURE = "UPLOAD_ONE_IMAGE_FAILURE";

export const DELETE_IMAGE_FROM_STORE = "DELETE_IMAGE_FROM_STORE";

export const DELETE_HEADER = "DELETE_HEADER";
