export const FETCH_SPEAKERS_REQUEST = "FETCH_SPEAKERS_REQUEST";
export const FETCH_SPEAKERS_SUCCESS = "FETCH_SPEAKERS_SUCCESS";
export const FETCH_SPEAKERS_FAILURE = "FETCH_SPEAKERS_FAILURE";

export const DELETE_SPEAKER_REQUEST = "DELETE_SPEAKER_REQUEST";
export const DELETE_SPEAKER_SUCCESS = "DELETE_SPEAKER_SUCCESS";
export const DELETE_SPEAKER_FAILURE = "DELETE_SPEAKER_FAILURE";

export const ADD_SPEAKER_REQUEST = "ADD_SPEAKER_REQUEST";
export const ADD_SPEAKER_SUCCESS = "ADD_SPEAKER_SUCCESS";
export const ADD_SPEAKER_FAILURE = "ADD_SPEAKER_FAILURE";
