export const FETCH_SPEAKERS_REQUEST = "FETCH_SPEAKERS_REQUEST";
export const FETCH_SPEAKERS_SUCCESS = "FETCH_SPEAKERS_SUCCESS";
export const FETCH_SPEAKERS_FAILURE = "FETCH_SPEAKERS_FAILURE";

export const DELETE_SPEAKER_REQUEST = "DELETE_SPEAKER_REQUEST";
export const DELETE_SPEAKER_SUCCESS = "DELETE_SPEAKER_SUCCESS";
export const DELETE_SPEAKER_FAILURE = "DELETE_SPEAKER_FAILURE";

export const ADD_SPEAKER_REQUEST = "ADD_SPEAKER_REQUEST";
export const ADD_SPEAKER_SUCCESS = "ADD_SPEAKER_SUCCESS";
export const ADD_SPEAKER_FAILURE = "ADD_SPEAKER_FAILURE";

export const SPEAKER_EDIT_REQUEST = "SPEAKER_EDIT_REQUEST";
export const SPEAKER_EDIT_SUCCESS = "SPEAKER_EDIT_SUCCESS";
export const SPEAKER_EDIT_FAILURE = "SPEAKER_EDIT_FAILURE";

export const FETCH_SPEAKERS_BY_PAGE_REQUEST = "FETCH_SPEAKERS_BY_PAGE_REQUEST";
export const FETCH_SPEAKERS_BY_PAGE_SUCCESS = "FETCH_SPEAKERS_BY_PAGE_SUCCESS";
export const FETCH_SPEAKERS_BY_PAGE_FAILURE = "FETCH_SPEAKERS_BY_PAGE_FAILURE";
